### ISSUE TITLE
Texte non centré sur Android

### ISSUE THREAD

**Issue by Yanonix** [yandam/adventure#1]
Le texte des cases n'est pas centré.

**Comment by Yanonix** [comment]
Sur un Nexus 5, c'est presque ça. Mais sur des versions plus anciennes (on peut descendre jusqu'à l'API 15, pas plus bas) comme le mien en API 16, ce n'est pas centré.

**Comment by mdamien** [comment]
Ok, ca doit venir du fait que j'utilise flexbox en css et que ca requiert un navigateur plutot recent. Moi ca passe niquel sur chrome de mon moto g.

Le truc c'est que la webview utilisais un vieux navigateur par défaut avant android 4.4

http://caniuse.com/#feat=flexbox

Pour les compats comme ca, c'est chaud de savoir jusqu'a où on veut aller

**Comment by mdamien** [comment]
On a le meme probleme sur safari. Faudrat juste reussir a forcer d'utiliser chrome (meme pour la webview) pour plus se soucier de tout ca.

**Comment by Yanonix** [comment]
Tu as testé avec quelle version du programme ? Après ou avant le commit 2be3587 ? Car il n'utilise plus les flexbox pour rendre compatible sur les vieux navigateurs.

**Comment by mdamien** [comment]
Ok, ben on close
