### ISSUE TITLE
Le click n'est pas pris si le doigt glisse (mode drag/drop)

### ISSUE THREAD

**Issue by Yanonix** [yandam/adventure#3]
Sur l'Android, il faut cliquer sans déraper. Pour le moment, je ne sais pas comment corriger cela, mais il le faut absolument. Le click doit rentrer en mode drag&drop ou en mode sélection (bien qu'il ne sélectionne rien).
C'est problématique quand tu es au volant car tu as vite faite de déraper sur l'écran. Je suis tombé dessus en essayant l'appli sur mon téléphone. Je ne comprenais pas pourquoi il prenait du temps à passer de menu en menu.

**Comment by mdamien** [comment]
Attend, c'est juste que dans l'app on attend "onClick" et pas "onTouch" faut que j'ajoute les events touch
